// Inspect Document Mapping
GET http://elasticsearch:9200/documents/_mapping


// Check Sample Document
GET http://elasticsearch:9200/documents/_doc/AodAd5IBsqFCQLJ6kEZY
Content-Type: application/json




// Test a Simplified Query:
// {
//     "query": {
//         "bool": {
//             "must": [
//                 {"term": {"project_id": user_project_id}},
//                 {"term": {"authorization_id": user_authorization_id}}
//             ]
//         }
//     }
// }


// Check Authorization ID Field Presence and Value
GET http://elasticsearch:9200/documents/_search
Content-Type: application/json
{
  "query": {
    "exists": {
      "field": "authorization_id"
    }
  }
}


// Fetch for the given authorization and project ids:
GET http://elasticsearch:9200/documents/_search
Content-Type: application/json
{
  "query": {
    "bool": {
        "must": [
            {"term": {"project_id": "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33"}},
            {"term": {"authorization_id": "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33"}}
        ]
    }
  },
  "_source": ["score", "category", "question", "answer", "document_id", "answer_instructions", "project_id", "authorization_id", "project_name"]
}

// Check Specific Values of authorization_id
GET /your_index/_search
{
  "size": 0,
  "aggs": {
    "unique_auth_ids": {
      "terms": {
        "field": "authorization_id",
        "size": 10
      }
    }
  }
}


// Examine the Query Execution Plan:
GET http://elasticsearch:9200/documents/_explain/AodAd5IBsqFCQLJ6kEZY
Content-Type: application/json
{
  "query": {
    "bool": {
        "must": [
            {"term": {"project_id": "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33"}},
            {"term": {"authorization_id": "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33"}}
        ]
    }
  }
}

GET http://elasticsearch:9200/documents/_search
Content-Type: application/json
{
  "query":{
    "bool": {
      "must": {
        "multi_match": {
          "query": "Bitte teilen Sie mir mit, wann die eingestellte Zinszahlung erfolgen wird.",
          "fields": [
            "question^2",
            "answer^2",
            "category",
            "project_name"
          ],
          "type": "best_fields"
        }
      },
      "filter": {
        "function_score": {
          "query": {
            "bool": {
              "must": [
                {
                  "term": {
                    "source_system": "evdi"
                  }
                }
              ],
              "should": [
                {
                  "bool": {
                    "must_not": {
                      "exists": {
                        "field": "project_id"
                      }
                    }
                  }
                },
                {
                  "bool": {
                    "must": [
                      {
                        "exists": {
                          "field": "project_id"
                        }
                      },
                      {
                        "term": {
                          "project_id": "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33"
                        }
                      },
                      {
                        "bool": {
                          "must_not": {
                            "exists": {
                              "field": "authorization_id"
                            }
                          }
                        }
                      }
                    ]
                  }
                },
                {
                  "bool": {
                    "must": [
                      {
                        "term": {
                          "project_id": "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33"
                        }
                      },
                      {
                        "terms": {
                          "authorization_id": [
                            "00000000-0000-0000-0000-000000000001",
                            "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33",
                            "d1f21f84-9eec-4d0b-a63a-bf656a28a256",
                            "716867b4-c28c-425e-94be-59886d853d49"
                          ]
                        }
                      }
                    ]
                  }
                }
              ],
              "minimum_should_match": 1
            }
          },
          "functions": [
            {
              "filter": {
                "bool": {
                  "must": [
                    {
                      "term": {
                        "project_id": "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33"
                      }
                    },
                    {
                      "terms": {
                        "authorization_id": [
                          "00000000-0000-0000-0000-000000000001",
                          "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33",
                          "d1f21f84-9eec-4d0b-a63a-bf656a28a256",
                          "716867b4-c28c-425e-94be-59886d853d49"
                        ]
                      }
                    }
                  ]
                }
              },
              "weight": 5
            },
            {
              "filter": {
                "bool": {
                  "must": [
                    {
                      "exists": {
                        "field": "project_id"
                      }
                    },
                    {
                      "term": {
                        "project_id": "0113C948-C9CE-4A3D-AF99-D66BDEDE7D33"
                      }
                    },
                    {
                      "bool": {
                        "must_not": {
                          "exists": {
                            "field": "authorization_id"
                          }
                        }
                      }
                    }
                  ]
                }
              },
              "weight": 3
            }
          ],
          "boost_mode": "sum"
        }
      }
    }
  },
  "_source": ["score", "category", "question", "answer", "document_id", "answer_instructions", "project_id", "authorization_id", "project_name"]
}