FROM ollama/ollama:latest as builder

RUN ollama serve & \
    sleep 10 && \
    ollama pull marco/em_german_mistral_v01

FROM ollama/ollama:latest

COPY --from=builder /root/.ollama/ /root/.ollama

ENTRYPOINT ["ollama"]
CMD ["serve"]
