services:
  notebook:
    image: quay.io/jupyter/minimal-notebook:latest
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/home/jovyan/work:cached
    env_file:
      - ./notebook/.env.dev
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=easy
      - CHOWN_EXTRA=/home/jovyan/work
      - CHOWN_EXTRA_OPTS=-R
    user: root

  app:
    image: python:3.12
    ports:
      - "8501:8501"
    depends_on:
      - elasticsearch
      - db
    env_file:
      - ./smart_mail/.env.dev
    environment:
      - STREAMLIT_SERVER_HEADLESS=true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.routing.allocation.disk.watermark.low=97%
      - cluster.routing.allocation.disk.watermark.high=98%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - cluster.routing.allocation.disk.watermark.flood_stage.frozen=99%

  db:
    image: postgres
    env_file:
      - ./smart_mail/.env.dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  mage:
    image: mageai/mageai:latest
    depends_on:
      - db
      - elasticsearch
    build:
      context: ./mage
    env_file:
      - ./mage/.env.dev
    ports:
      - "6789:6789"
    volumes:
      - .:/zoomcamp-smart-mail:cached
    restart: on-failure:2

volumes:
  db_data:
